### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by denikson** [BepInEx/HarmonyX#2]
**Current state**: the library can successfully work with existing Harmony patches. However, regular use is discouraged, as some features are not yet ported to MonoMod.

## Porting tasks
- [x] Port main the main patcher code to use `MonoMod.ILHook`
- [x] Remove unnecessary internal code (shared state, self-patching) 
- [x] Port reverse patchers
- [x] Port basic logging
- [x] Update `AccessTools` and other helpers to use `DynamicMethodDefinition`

## New features
- [x] Better locking logic
- [x] New logging system
- [ ] New patch type: IL manipulators
- [x] New patch type: native detours (ability to hook icalls)
- [x] Merge code with `BepInEx.Harmony`

## Misc
- [ ] Document patch types: finalizers, reverse patchers

## On hold

These features are on hold until we assess a need for them better
- [ ] Async patching
- [ ] Additional `HarmonyPatch` attributes

**Comment by denikson** [comment]
Closing in favour of #15
